defaults:
  - model: dino
  - data: default
  - train: default
  - loss: clip
  - test: default
  - _self_

hydra:
  run:
    dir: outputs/visualization/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true

device: cuda
seed: 7
mode: visualize
